# Generated by Django 4.2.5 on 2023-09-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vocab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_ko", models.CharField(max_length=100)),
                ("word_en", models.CharField(max_length=100)),
                ("sentence", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("complete", models.BooleanField(default=False)),
                ("important", models.BooleanField(default=False)),
                ("failed", models.BooleanField(default=False)),
            ],
        ),
    ]
