# Generated by Django 4.2.5 on 2023-09-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("langapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocab",
            name="language",
            field=models.CharField(
                choices=[
                    ("en-US", "English"),
                    ("ja-JP", "Japanese"),
                    ("zh-CN", "Chinese"),
                    ("es-ES", "Spanish"),
                    ("fr-FR", "French"),
                    ("de-DE", "German"),
                    ("ru-RU", "Russian"),
                ],
                default="en-US",
                max_length=10,
                verbose_name="단어 언어",
            ),
        ),
    ]
