# Generated by Django 4.2.5 on 2023-09-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("langapp", "0002_vocab_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocab",
            name="sentence",
            field=models.TextField(blank=True, verbose_name="예문"),
        ),
        migrations.AlterField(
            model_name="vocab",
            name="word_en",
            field=models.CharField(blank=True, max_length=100, verbose_name="외울 단어"),
        ),
        migrations.AlterField(
            model_name="vocab",
            name="word_ko",
            field=models.CharField(max_length=100, verbose_name="외울 단어(한국어)"),
        ),
    ]
