# Generated by Django 4.2.5 on 2023-09-23 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("langapp", "0003_alter_vocab_sentence_alter_vocab_word_en_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vocab",
            old_name="word_en",
            new_name="word_fo",
        ),
    ]
