# Generated by Django 4.2.5 on 2023-09-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("langapp", "0004_rename_word_en_vocab_word_fo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocab",
            name="language",
            field=models.CharField(
                choices=[
                    ("en-US", "English"),
                    ("ja-JP", "Japanese"),
                    ("zh-CN", "Chinese"),
                    ("es-ES", "Spanish"),
                    ("fr-FR", "French"),
                    ("de-DE", "German"),
                    ("ru-RU", "Russian"),
                ],
                default="en-US",
                max_length=10,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="vocab",
            name="sentence",
            field=models.TextField(blank=True, verbose_name="Sentence"),
        ),
        migrations.AlterField(
            model_name="vocab",
            name="word_fo",
            field=models.CharField(blank=True, max_length=100, verbose_name="Voacab"),
        ),
        migrations.AlterField(
            model_name="vocab",
            name="word_ko",
            field=models.CharField(max_length=100, verbose_name="Meaning"),
        ),
    ]
