# Generated by Django 4.2.5 on 2023-09-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("langapp", "0005_alter_vocab_language_alter_vocab_sentence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocab",
            name="word_fo",
            field=models.CharField(blank=True, max_length=100, verbose_name="Vocab"),
        ),
    ]
